
naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  client:
<<<<<<< HEAD
    id: sGMfV60HXEqJdhQPG7Qh
    secret: zkeFtmcf8P
=======
    id: Zi3o1uQftp59zuIqEAz4
    secret: iy6YKSWpLM
>>>>>>> 26b162e (test)
